### ISSUE TITLE
counter_cache values are not updated

### ISSUE THREAD

**Issue by jamesfzhang** [jamis/bulk_insert#12]
It seems like `counter_cache` columns aren't updated after a bulk insert. What's the best way to remedy this?

It would be bad to have to run `reset_counter` on every record that's affected.

**Comment by jamis** [comment]
Right, they will not be updated, because (by design) this library does not run before/after hooks, and in fact skips the entire save pipeline in ActiveRecord. (This allows simple inserts to be blazing fast.) If you need counter cache columns to be updated, you'll need to do it yourself, keeping track of what's being inserted, and who the parent objects are, and running SQL statements to update those columns.

If you can come up with a way to automate that without adding overhead for other inserts, I'd be willing to consider a pull request.
