### ISSUE TITLE
Bulk Insert Concurrency

### ISSUE THREAD

**Issue by sithara** [jamis/bulk_insert#24]
When trying to insert 60k records in a go , the total results in the database is 60k * 7 

```
ActiveRecord::Base.establish_connection(adapter: 'sqlserver', host: "xxx", username: "xxx", password: "xxx", database: "xxx", azure: true, port: 1433, timeout: 5000)

class Report < ActiveRecord::Base
  self.primary_key = 'id'
end

my_array = [] #count of 100000 records
Report.bulk_insert(:account_owner_id) do |worker|
  my_array.each do |arr|
    worker.add account_owner_id: arr[0]
  end
end
```

This issue occurs when I add this to a cron/scheduler. This also occurs when the table to which insertion happens have a lot of data

**Comment by 9mm** [comment]
Hmm this seems quite bad, as if I shouldn't use this gem... you're saying you get tons of duplicate records and whatnot?

**Comment by mberlanda** [comment]
Hi @sithara, could you post the schema of the table you are inserting into? Did you put any constraint on it? It would be very useful to have a test to reproduce the issue in order to better understand your use case.

I am using this gem with a cron but I have never experienced something like what you posted.

**Comment by jamis** [comment]
There hasn't been any activity on this for a few months, so I'm going to close this issue. If it is still a problem, please feel free to reopen it.
