### ISSUE TITLE
Not null contraint but PARAM exists

### ISSUE THREAD

**Issue by JulioOrellana** [jamis/bulk_insert#30]
Hello, I am trying to use bulk_insert on a model whose not null constraint is ID, the problema is I have an object with ID on it's value

![image](https://user-images.githubusercontent.com/10372340/37872495-6b131d3e-2fdf-11e8-92b2-b27b6b400e3b.png)

But when I try to use bulk_insert on it:

![image](https://user-images.githubusercontent.com/10372340/37872502-7d5e41f8-2fdf-11e8-9d2e-a1640e07f579.png)

My schema.rb of Tweet

![image](https://user-images.githubusercontent.com/10372340/37872508-a2c9322c-2fdf-11e8-8309-2e338c5fc008.png)

Any ideas how to fix this?

**Comment by mberlanda** [comment]
Hey @JulioOrellana, could you provide a little bit more of context?

- Which ruby, rails and gem version are you using?
- I do not see the `:id` column in your schema but in your `Tweet` model looks correct. If you try `Tweer.create!(tw_tweet)` would you get any exception?
- what is the content of `tw_tweet`?
- could you copy paste your console output instead of adding screenshots?

**Comment by jamis** [comment]
As the OP hasn't responded to a request for more info, I'm going to close this issue. @JulioOrellana -- if this is still a problem, feel free to reopen it with a bit more information, as requested by @mberlanda. Thanks!
