### ISSUE TITLE
NoMethodError: undefined method 'result_sets' for nil:NilClass

### ISSUE THREAD

**Issue by theodorosidmar** [jamis/bulk_insert#35]
Hello there!

I just updated to latest version [v1.7.0](https://github.com/jamis/bulk_insert/releases/tag/v1.7.0) because I'm trying to use [Return Primary Keys](https://github.com/jamis/bulk_insert/tree/v1.7.0#return-primary-keys-postgresql-postgis) feature.

So, I just wrote down:
```ruby
while my_condition
  packs << [some_value, another_value, Time.now, Time.now]
  # decrement my_condition
end

destination_columns = [:column1, :column2, :created_at, :updated_at]
worker = Pack.bulk_insert(*destination_columns, return_primary_keys: true) { |worker|
  packs.each { |pack|
    worker.add pack
  }
  # That's how I use bulk_insert everywhere
}
```

I'm doing that because I need to associate these packs with another model. Sometime I need to write `pack.my_model_associated << [ids]` or just something like that. I do not know if it is possible not using [Return Primary Keys](https://github.com/jamis/bulk_insert/tree/v1.7.0#return-primary-keys-postgresql-postgis) feature. I was thinking about something like:
```ruby
worker.result_sets.each { |pack|
  pack.my_model_associated << [1, 2, 3, 4]
  pack.save!
}
```

I know `worker.result_sets` is an `ActiveRecord::Result` and does not contain `each` method. But like I said, it is just an idea. I was going to code **something like that**.
Anyway, I get the error:
`NoMethodError: undefined method 'result_sets' for nil:NilClass`, because my `worker` is `nil`.

I cloned the repository and modified line [22](https://github.com/jamis/bulk_insert/blob/861d5eda72e0e483740f096252baab2ab4b65479/lib/bulk_insert.rb#L22) in [lib/bulk_insert.rb](https://github.com/jamis/bulk_insert/blob/v1.7.0/lib/bulk_insert.rb). I returned `worker` instead of `nil` even on `block_given?` is `true` and the error stopped happening. But, I really don't know why I did that and I was not confident, so I did not submit a pull request or something else (I'm not an expert ruby developer). I just know `worker.result_sets` was not `nil` anymore. Although I couldn't do what I wanted (bulk_insert packs and relate all them with `my_model_associated` quickly).

Could you help me?

Thanks.

**Comment by butnaruandrei** [comment]
Hi @theodorosidmar ,

I had the same issue, but after some digging into the gem's code I found that you'll have to create a **bulk_insert** worker first. Having this worker, you can add the resources you want to save in bulk and after that you'll have to manually call the **save!** method. 

```ruby
# create a worker instance
worker = UserRole.bulk_insert(return_primary_keys: true)
# add resources that you want to save in bulk
worker.add(...)
# manually save
worker.save!
# you can access the result_sets afterwards
worker.result_sets
```

In order to extract de ids you can try this `ids = worker.result_sets.map(&:rows).flatten`. I'm not sure it will work on every case, but on mine it did work. 

Regards,
Andrei

**Comment by dhempy** [comment]
Same here. Thanks for the fix, @butnaruandrei !

**Comment by jamis** [comment]
Good explanation, @butnaruandrei, thanks for chiming in with a solution! Looking at the `bulk_insert` method, I would not be opposed to a PR that made the method always return the worker, instead of returning `nil` in most cases. I think that would be a more intuitive way of getting at (for example) the `result_sets` array.

For now, as this issue isn't really reporting a bug, but just a limitation of the way it is currently implemented, I'm going to close it. Thanks!
